/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as AbsencesRouteImport } from './routes/absences'
import { Route as IndexRouteImport } from './routes/index'

const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesRoute = AbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/checklists': typeof ChecklistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/checklists': typeof ChecklistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/checklists': typeof ChecklistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/absences' | '/checklists'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/absences' | '/checklists'
  id: '__root__' | '/' | '/absences' | '/checklists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsencesRoute: typeof AbsencesRoute
  ChecklistsRoute: typeof ChecklistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsencesRoute: AbsencesRoute,
  ChecklistsRoute: ChecklistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
